name = "PowerLawSamplers"
uuid = "ea71c90e-cdc5-43db-a32d-9c22f1535540"
authors = ["Kieran Marray"]
version = "0.1.0"

[compat]
julia = "1"
SpecialFunctions = "2.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
